# Generated by Django 5.0.1 on 2024-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveManagement',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
                ('leavedate', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('leavebucket', models.CharField(max_length=100)),
                ('hr_approval', models.CharField(default='FALSE', max_length=100)),
                ('TL_approval', models.CharField(default='FALSE', max_length=100)),
            ],
        ),
    ]
