# Generated by Django 5.0.1 on 2024-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERMApp', '0002_leavemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('DOJ', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('avl_leaves', models.CharField(max_length=100)),
            ],
        ),
    ]
